spring.application.name=demo
server.port=8080

# Logger Configuration
logger.level=INFO
logger.format=JSON

# Secrets Configuration
secrets.source=ENV

# File Manager Configuration
filemanager.storage.type=LOCAL
filemanager.base.path=./data
